### ISSUE TITLE
Infografía: Calidad de software

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/infografia-de-calidad-team-noble#2]
[Calidad de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-team-noble/files/8818263/Calidad.de.software.pdf)

**Comment by josealfredo79** [comment]
Falta la calificación...

**Comment by Ferch0419** [comment]
Buen trabajo. Calificación 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
