### ISSUE TITLE
Infografía Calidad de software 

### ISSUE THREAD

**Issue by IsraelNicolas61** [SistemasTecTlaxiaco/infografia-de-calidad-team-noble#3]
[Infografia Calidad de Software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-team-noble/files/8818364/Infografia.Calidad.de.Software.pdf)

**Comment by Nayee123** [comment]
Muy buen trabajo 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
