### ISSUE TITLE
Calidad de Software

### ISSUE THREAD

**Issue by IMA-G** [SistemasTecTlaxiaco/infografia-de-calidad-team-noble#4]
[Infografia Calidad de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-team-noble/files/8818383/Infografia.Calidad.de.software.pdf)

**Comment by CxrlosMX** [comment]
Calificación obtenida: 20/20 
Trabajo bien realizado!

**Comment by CxrlosMX** [comment]
Calificación obtenida: 20/20 
Trabajo bien realizado!

**Comment by josealfredo79** [comment]
Trabajo bien realizado...
