### ISSUE TITLE
Infografía -Calidad de Software

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/infografia-de-calidad-team-noble#5]
[Infografia Claidad de software.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-team-noble/files/8819584/Infografia.Claidad.de.software.pdf)

**Comment by ArturoAngonJose** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
